from .UploadingTextFiles import upload_text_file_router
from .ManageMongoCollectionRoutes import create_collection_in_mongo_router,delete_collection_in_mongo_router
from .ChunkDocument import chunk_document_router
from .UploadingMultipleFiles import upload_multiple_text_files_router
from .EmeddingAndPushing import embedding_and_pushing_router
from .CreateVectorCollection import create_vector_collection_router